### ISSUE TITLE
Support for title properties on circle layers

### ISSUE THREAD

**Issue by n0rdlicht** [cividi/spatial-data-package-platform#12]
For circle layers with mediatype `application/vnd.simplestyles-extended` while adding `L.Circle` objects a popover should be attached if the feature has `title` and/or `description` attribute present as implemented by mapbox.js for `application/geo+json` layers.

**Comment by loleg** [comment]
There is an example from the [Mapbox docs](https://docs.mapbox.com/help/tutorials/make-a-heatmap-with-mapbox-gl-js/#add-some-additional-interactivity)

**Comment by ratron** [comment]
@n0rdlicht do you happen have an example snapshot on stage (or somewhere else) where circles have these attributes that i could test this feature with?

**Comment by n0rdlicht** [comment]
Updated an old example to have both title and description fields: https://stage.gemeindescan.ch/de/FQJYNA/

<img width="300" alt="Screenshot 2021-06-30 at 10 35 25" src="https://user-images.githubusercontent.com/1425577/123929193-e2e25800-d98e-11eb-83db-871df85e8fac.png">

**Comment by ratron** [comment]
I created a new branch circle-clickable and implemented this feature. @n0rdlicht Do you want to test it there or should i merge it to main?

**Comment by n0rdlicht** [comment]
Thanks. I'll have a look and let you know.

**Comment by n0rdlicht** [comment]
Seems to work as expected, feel free to merge and close.
