### ISSUE TITLE
Fix OpenStreetMap attribution in new municipality mode

### ISSUE THREAD

**Issue by n0rdlicht** [cividi/spatial-data-package-platform#120]
When opening a `.../new-municipality/...` link no Mapbox/OpenStreetMap attribution is present.

**Comment by n0rdlicht** [comment]
Where:
Essentially every map. Currently these are only present on "snapshot maps", hence the request to addit to the non-snapshot ones. If we have a version that makes sense in both contexts (namely with and without a legend I assume) would make sense to use the same component/setup yes.

Legal part, based on https://docs.mapbox.com/help/getting-started/attribution/:
As long as the maps are served by Mapbox and we are using Mapbox JS, the logo seems to be required, however can be moved to a different location. Text wise we would need to add an "improve this map" link.

Logo:
> The Mapbox logo is a small image containing the stylized word "Mapbox". It typically resides on the bottom left corner of a map. While you may move the logo to a different corner of the map, we require the Mapbox logo to appear on our maps so that Mapbox and its maps get proper credit.

Text

> The text attribution contains at least three links: © Mapbox, © OpenStreetMap and Improve this map. You must properly attribute and link Mapbox and OpenStreetMap when using the Mapbox Streets tileset. Some other Mapbox-provided tilesets require additional attribution which is stored in the TileJSON of the tileset. If you are using Mapbox software to render a map based entirely on data from a non-Mapbox source, you may omit the text attribution but must still display the Mapbox logo.

https://docs.mapbox.com/help/getting-started/attribution/#text-attribution

**Comment by ratron** [comment]
@n0rdlicht the attribution consists of all three links and looks like this:
![image](https://user-images.githubusercontent.com/14057805/123960319-71ff6800-d9af-11eb-9142-a587ee25a39e.png)

**Comment by ratron** [comment]
@n0rdlicht you can check this out on main ... it seemed such a simple/local change that i did not create a separate branch .

**Comment by n0rdlicht** [comment]
👍

Think we need to enforce the attribution also on snapshots unfortunately, as it can easily go missing there as well. Either by adding the same box (clashes with the legend overlay) or adding two (three?) entries under "Quellenangaben" out of the box, adding the ones present in the data package.

Bigger context: See the map background more and more as a platform feature rather than something the snapshot should define, hence the attribution should also be handled by the platform.

**Comment by ratron** [comment]
Do you @n0rdlicht have a preference if the attribution from "new municipality" is also shown on the snapshot (less work) or if it's added to the info box (requires  0.5 - 1h)

**Comment by n0rdlicht** [comment]
> Do you @n0rdlicht have a preference if the attribution from "new municipality" is also shown on the snapshot (less work) or if it's added to the info box (requires  0.5 - 1h)  

The map background should be platform and independent from the data layers (though currently part of the snapshot json). Hence I vote option 1.

**Comment by ratron** [comment]
OK. Attribution is integrated in Map like so (Info Box moves slightly up):
![image](https://user-images.githubusercontent.com/14057805/124633052-32d88780-de85-11eb-8cc7-6d6274ad3c59.png)

(changed directly in main)
