### ISSUE TITLE
License Notice

### ISSUE THREAD

**Issue by n0rdlicht** [cividi/spatial-data-package-platform#125]
Compile third party license notices from dependencies and add to /imprint page.

**Comment by ratron** [comment]
Which Licences? 
The Packages from package.json
Only the main technologies (Django Vue Vuetify)
Or all Packages that are used? ("yarn list" shows over 4'000 Packages)

**Comment by n0rdlicht** [comment]
Open for your suggestion here. Might need a little research for quality but not sure I/we can answer it that easily as it depends a bit on the licenses themselves. Hence I would rely on a third party license notice generator each (to be researched) to generate a `vue/NOTICE.md` and `django/NOTICE.md` from the `packages.json` and `requirements.txt` respectively. Maybe even adding a concated `NOTICE.md` to the root level, which can then be turned into html and inserted into `imprint.vue`.

**Comment by yvess** [comment]
a followup question

I have seen there is `yarn list licenses` which shows all licenses used by all packages. Is the goal to see which different licenses are used in the project and the dependencies. So we could reduce the set to perhaps for example the 20 different license used. Or it's more important to have a package to license lookup table?

**Comment by n0rdlicht** [comment]
Main goal I'd see to comply with license terms set by dependencies, hence it is related to the individual license what is needed here.

e.g. afaik software licensed as MIT requires a copyright and license notice to be included in distributed copies, in our case a deployed instance not so much the github repo as those packages are linked but not bundled directly. However, that is not the case for the deployed instance.

Hence I was looking a bit at generators taking the specific license notice/copyright requirements into account when compiling a notice to include in shipping versions.

**Comment by ratron** [comment]
The command `yarn licenses generate-disclaimer` will collect all the license information of all packages. It's a 1MB big text file:
[licenses-vue.txt](https://github.com/cividi/spatial-data-package-platform/files/6791652/licenses-vue.txt)

**Comment by n0rdlicht** [comment]
Using the built in option sounds good.
How is the clean-up done? If automatic I don‘t think this is an issue as it also allows to track changes if new dependencies get added/dependencies change if we capture them in a NOTICE.md before adding it.
Did you find something similar on the python/django side?

Size: Hence you would prefer a separate page for these or remain with the original plan to include it in the imprint page?

**Comment by ratron** [comment]
I did the clean up manually: looking for standard licenses and use find and replace.
Because of it's size, i would not include it in the imprint page. I'd suggest a link from the imprint to a separate license information page. 

for python, there is pip-licenses
https://pypi.org/project/pip-licenses/

more options: https://stackoverflow.com/questions/19086030/can-pip-or-setuptools-distribute-etc-list-the-license-used-by-each-install

**Comment by n0rdlicht** [comment]
Then I’d go for the automatically generated version from both (yarn and pip, no cleanup) even if noisier but less maintenance and as you suggested merged into a in a separate `/notices` page (linked from imprint) for now.

**Comment by ratron** [comment]
I created a licenses-python.md with the pip-licenses package by running
`pip-licenses --with-system --order=license --format=markdown`

I also created a licenses-js.json by running 
`yarn licenses list --json > licenses-js.json`
..which I then converted to an MD file using this gist:
https://gist.github.com/huntie/df528a790f457ceac2e8bd7b3221b763

Now we have two *.md files and I converted these to HTML and created the Notice.vue view. See:
https://github.com/cividi/spatial-data-package-platform/commit/ff701ceed0c1fd491cb4e4d993fb9afd3d9a51ff


The MD to HTML could be automated with something like:
https://yarnpkg.com/package/vue-markdown
https://yarnpkg.com/package/vue-markdown-loader
... but at some point we would need to add the titles and the translations.

**Comment by n0rdlicht** [comment]
Thanks @ratron. Tried on stage, looking good, think we can merge this.
