### ISSUE TITLE
Show version number

### ISSUE THREAD

**Issue by n0rdlicht** [cividi/spatial-data-package-platform#15]
Print out deployed frontend / backend versions.

Frontend: could be at the bottom of the home / root page.
Backend: either on the login pages or in the django admin dashboard

**Comment by n0rdlicht** [comment]
Moved to 0.8.0

**Comment by ratron** [comment]
For the Django backend, Yves and I would suggest the Footer. Is that OK?

**Comment by n0rdlicht** [comment]
Footer sounds perfect.

**Comment by glaand** [comment]
https://github.com/cividi/spatial-data-package-platform/pull/132
