### ISSUE TITLE
Fix unit tests

### ISSUE THREAD

**Issue by n0rdlicht** [cividi/spatial-data-package-platform#28]
Both the runner and some of the unit tests seem broken currently.

## [Test Action Runner](https://github.com/cividi/spatial-data-package-platform/actions?query=workflow%3ATests)

During setup the following error happens:

```sh
Creating spatial-data-package-platform_www_1    ... done
cd django && make init
make[1]: Entering directory '/home/runner/work/spatial-data-package-platform/spatial-data-package-platform/django'
make symlinks
make[2]: Entering directory '/home/runner/work/spatial-data-package-platform/spatial-data-package-platform/django'
docker-compose exec django sh -c "cd /var/services/django; ln -s media downloads"
the input device is not a TTY
make[2]: *** [symlinks] Error 1
Makefile:33: recipe for target 'symlinks' failed
make[2]: Leaving directory '/home/runner/work/spatial-data-package-platform/spatial-data-package-platform/django'
make[1]: *** [init] Error 2
make: *** [init] Error 2
Makefile:58: recipe for target 'init' failed
make[1]: Leaving directory '/home/runner/work/spatial-data-package-platform/spatial-data-package-platform/django'
Makefile:13: recipe for target 'init' failed
Error: Process completed with exit code 2.
```

### django

Running `cd django && make tests` locally on `master` results in the following output:

```sh
=========================================================== short test summary info ===========================================================
ERROR gsmap/tests.py::test_municipalities_exists - django.core.management.base.CommandError: No fixture named 'sites.site' found.
ERROR gsmap/tests.py::test_snapshots_exists - django.core.management.base.CommandError: No fixture named 'sites.site' found.
======================================================= 324 warnings, 2 errors in 2.21s =======================================================
```

### Vue

Running `cd vue && make tests` locally on `master` results in the following output:

```sh
vue % make tests
docker-compose exec vue yarn test
yarn run v1.19.2
$ ava --verbose --timeout=30s test/**/*.spec.js

  ✖ SnapshotList.vue 

  1 test failed

  SnapshotList.vue

  test/components/SnapshotList.spec.js:41

  Difference:

  - 0
  + 2

  › test/components/SnapshotList.spec.js:41:5

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by loleg** [comment]
+1

@yvess any inputs on the kind of work required here?

**Comment by yvess** [comment]
see #74 test runner works now

**Comment by n0rdlicht** [comment]
> see #74 test runner works now

tried that PR locally. See my output below.
<details>
<pre>
thorben.cividi@book spatial-data-package-platform % make tests
cd django && make tests
docker-compose exec  django pytest --create-db
======================================================== test session starts ========================================================
platform linux -- Python 3.8.5, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
django: settings: main.settings_tests (from ini)
rootdir: /opt/app, configfile: pytest.ini
plugins: django-4.1.0
collected 2 items                                                                                                                   

gsmap/tests.py EE                                                                                                             [100%]

============================================================== ERRORS ===============================================================
___________________________________________ ERROR at setup of test_municipalities_exists ____________________________________________

request = <SubRequest '_django_db_marker' for <Function test_municipalities_exists>>

    @pytest.fixture(autouse=True)
    def _django_db_marker(request):
        """Implement the django_db marker, internal to pytest-django.
    
        This will dynamically request the ``db``, ``transactional_db`` or
        ``django_db_reset_sequences`` fixtures as required by the django_db marker.
        """
        marker = request.node.get_closest_marker("django_db")
        if marker:
            transaction, reset_sequences = validate_django_db(marker)
            if reset_sequences:
                request.getfixturevalue("django_db_reset_sequences")
            elif transaction:
                request.getfixturevalue("transactional_db")
            else:
>               request.getfixturevalue("db")

/usr/lib/python3.8/site-packages/pytest_django/plugin.py:436: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/opt/app/conftest.py:8: in django_db_setup
    call_command('loaddata', 'fixtures-tests/sites.site.json')
/usr/lib/python3.8/site-packages/django/core/management/__init__.py:168: in call_command
    return command.execute(*args, **defaults)
/usr/lib/python3.8/site-packages/django/core/management/base.py:371: in execute
    output = self.handle(*args, **options)
/usr/lib/python3.8/site-packages/django/core/management/commands/loaddata.py:72: in handle
    self.loaddata(fixture_labels)
/usr/lib/python3.8/site-packages/django/core/management/commands/loaddata.py:106: in loaddata
    if self.find_fixtures(fixture_label):
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <django.core.management.commands.loaddata.Command object at 0x400b47f9a0>, fixture_label = 'fixtures-tests/sites.site.json'

    @functools.lru_cache(maxsize=None)
    def find_fixtures(self, fixture_label):
        """Find fixture files for a given label."""
        if fixture_label == READ_STDIN:
            return [(READ_STDIN, None, READ_STDIN)]
    
        fixture_name, ser_fmt, cmp_fmt = self.parse_name(fixture_label)
        databases = [self.using, None]
        cmp_fmts = list(self.compression_formats) if cmp_fmt is None else [cmp_fmt]
        ser_fmts = serializers.get_public_serializer_formats() if ser_fmt is None else [ser_fmt]
    
        if self.verbosity >= 2:
            self.stdout.write("Loading '%s' fixtures..." % fixture_name)
    
        if os.path.isabs(fixture_name):
            fixture_dirs = [os.path.dirname(fixture_name)]
            fixture_name = os.path.basename(fixture_name)
        else:
            fixture_dirs = self.fixture_dirs
            if os.path.sep in os.path.normpath(fixture_name):
                fixture_dirs = [os.path.join(dir_, os.path.dirname(fixture_name))
                                for dir_ in fixture_dirs]
                fixture_name = os.path.basename(fixture_name)
    
        suffixes = (
            '.'.join(ext for ext in combo if ext)
            for combo in product(databases, ser_fmts, cmp_fmts)
        )
        targets = {'.'.join((fixture_name, suffix)) for suffix in suffixes}
    
        fixture_files = []
        for fixture_dir in fixture_dirs:
            if self.verbosity >= 2:
                self.stdout.write("Checking %s for fixtures..." % humanize(fixture_dir))
            fixture_files_in_dir = []
            path = os.path.join(fixture_dir, fixture_name)
            for candidate in glob.iglob(glob.escape(path) + '*'):
                if os.path.basename(candidate) in targets:
                    # Save the fixture_dir and fixture_name for future error messages.
                    fixture_files_in_dir.append((candidate, fixture_dir, fixture_name))
    
            if self.verbosity >= 2 and not fixture_files_in_dir:
                self.stdout.write("No fixture '%s' in %s." %
                                  (fixture_name, humanize(fixture_dir)))
    
            # Check kept for backwards-compatibility; it isn't clear why
            # duplicates are only allowed in different directories.
            if len(fixture_files_in_dir) > 1:
                raise CommandError(
                    "Multiple fixtures named '%s' in %s. Aborting." %
                    (fixture_name, humanize(fixture_dir)))
            fixture_files.extend(fixture_files_in_dir)
    
        if not fixture_files:
>           raise CommandError("No fixture named '%s' found." % fixture_name)
E           django.core.management.base.CommandError: No fixture named 'sites.site' found.

/usr/lib/python3.8/site-packages/django/core/management/commands/loaddata.py:271: CommandError
------------------------------------------------------- Captured stderr setup -------------------------------------------------------
Got an error creating the test database: database "test_webui-tests    " already exists

______________________________________________ ERROR at setup of test_snapshots_exists ______________________________________________

request = <SubRequest '_django_db_marker' for <Function test_snapshots_exists>>

    @pytest.fixture(autouse=True)
    def _django_db_marker(request):
        """Implement the django_db marker, internal to pytest-django.
    
        This will dynamically request the ``db``, ``transactional_db`` or
        ``django_db_reset_sequences`` fixtures as required by the django_db marker.
        """
        marker = request.node.get_closest_marker("django_db")
        if marker:
            transaction, reset_sequences = validate_django_db(marker)
            if reset_sequences:
                request.getfixturevalue("django_db_reset_sequences")
            elif transaction:
                request.getfixturevalue("transactional_db")
            else:
>               request.getfixturevalue("db")

/usr/lib/python3.8/site-packages/pytest_django/plugin.py:436: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/opt/app/conftest.py:8: in django_db_setup
    call_command('loaddata', 'fixtures-tests/sites.site.json')
/usr/lib/python3.8/site-packages/django/core/management/__init__.py:168: in call_command
    return command.execute(*args, **defaults)
/usr/lib/python3.8/site-packages/django/core/management/base.py:371: in execute
    output = self.handle(*args, **options)
/usr/lib/python3.8/site-packages/django/core/management/commands/loaddata.py:72: in handle
    self.loaddata(fixture_labels)
/usr/lib/python3.8/site-packages/django/core/management/commands/loaddata.py:106: in loaddata
    if self.find_fixtures(fixture_label):
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <django.core.management.commands.loaddata.Command object at 0x400b47f9a0>, fixture_label = 'fixtures-tests/sites.site.json'

    @functools.lru_cache(maxsize=None)
    def find_fixtures(self, fixture_label):
        """Find fixture files for a given label."""
        if fixture_label == READ_STDIN:
            return [(READ_STDIN, None, READ_STDIN)]
    
        fixture_name, ser_fmt, cmp_fmt = self.parse_name(fixture_label)
        databases = [self.using, None]
        cmp_fmts = list(self.compression_formats) if cmp_fmt is None else [cmp_fmt]
        ser_fmts = serializers.get_public_serializer_formats() if ser_fmt is None else [ser_fmt]
    
        if self.verbosity >= 2:
            self.stdout.write("Loading '%s' fixtures..." % fixture_name)
    
        if os.path.isabs(fixture_name):
            fixture_dirs = [os.path.dirname(fixture_name)]
            fixture_name = os.path.basename(fixture_name)
        else:
            fixture_dirs = self.fixture_dirs
            if os.path.sep in os.path.normpath(fixture_name):
                fixture_dirs = [os.path.join(dir_, os.path.dirname(fixture_name))
                                for dir_ in fixture_dirs]
                fixture_name = os.path.basename(fixture_name)
    
        suffixes = (
            '.'.join(ext for ext in combo if ext)
            for combo in product(databases, ser_fmts, cmp_fmts)
        )
        targets = {'.'.join((fixture_name, suffix)) for suffix in suffixes}
    
        fixture_files = []
        for fixture_dir in fixture_dirs:
            if self.verbosity >= 2:
                self.stdout.write("Checking %s for fixtures..." % humanize(fixture_dir))
            fixture_files_in_dir = []
            path = os.path.join(fixture_dir, fixture_name)
            for candidate in glob.iglob(glob.escape(path) + '*'):
                if os.path.basename(candidate) in targets:
                    # Save the fixture_dir and fixture_name for future error messages.
                    fixture_files_in_dir.append((candidate, fixture_dir, fixture_name))
    
            if self.verbosity >= 2 and not fixture_files_in_dir:
                self.stdout.write("No fixture '%s' in %s." %
                                  (fixture_name, humanize(fixture_dir)))
    
            # Check kept for backwards-compatibility; it isn't clear why
            # duplicates are only allowed in different directories.
            if len(fixture_files_in_dir) > 1:
                raise CommandError(
                    "Multiple fixtures named '%s' in %s. Aborting." %
                    (fixture_name, humanize(fixture_dir)))
            fixture_files.extend(fixture_files_in_dir)
    
        if not fixture_files:
>           raise CommandError("No fixture named '%s' found." % fixture_name)
E           django.core.management.base.CommandError: No fixture named 'sites.site' found.

/usr/lib/python3.8/site-packages/django/core/management/commands/loaddata.py:271: CommandError
========================================================= warnings summary ==========================================================
../../usr/lib/python3.8/site-packages/graphene/types/field.py:2
  /usr/lib/python3.8/site-packages/graphene/types/field.py:2: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    from collections import Mapping, OrderedDict

../../usr/lib/python3.8/site-packages/graphene/relay/connection.py:2
  /usr/lib/python3.8/site-packages/graphene/relay/connection.py:2: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    from collections import Iterable, OrderedDict

../../usr/lib/python3.8/site-packages/packaging/version.py:127: 312 warnings
  /usr/lib/python3.8/site-packages/packaging/version.py:127: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
    warnings.warn(

../../usr/lib/python3.8/site-packages/django_apscheduler/models.py:17
  /usr/lib/python3.8/site-packages/django_apscheduler/models.py:17: RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().
    max_length=255, primary_key=True, help_text=_("Unique id for this job.")

../../usr/lib/python3.8/site-packages/django_apscheduler/models.py:24
  /usr/lib/python3.8/site-packages/django_apscheduler/models.py:24: RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().
    help_text=_(

../../usr/lib/python3.8/site-packages/django_apscheduler/models.py:64
  /usr/lib/python3.8/site-packages/django_apscheduler/models.py:64: RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().
    primary_key=True, help_text=_("Unique ID for this job execution.")

../../usr/lib/python3.8/site-packages/django_apscheduler/models.py:70
  /usr/lib/python3.8/site-packages/django_apscheduler/models.py:70: RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().
    help_text=_("The job that this execution relates to."),

../../usr/lib/python3.8/site-packages/django_apscheduler/models.py:78
  /usr/lib/python3.8/site-packages/django_apscheduler/models.py:78: RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().
    help_text=_("The current status of this job execution."),

../../usr/lib/python3.8/site-packages/django_apscheduler/models.py:82
  /usr/lib/python3.8/site-packages/django_apscheduler/models.py:82: RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().
    db_index=True, help_text=_("Date and time at which this job was executed."),

../../usr/lib/python3.8/site-packages/django_apscheduler/models.py:92
  /usr/lib/python3.8/site-packages/django_apscheduler/models.py:92: RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().
    help_text=_("Total run time of this job (in seconds)."),

../../usr/lib/python3.8/site-packages/django_apscheduler/models.py:100
  /usr/lib/python3.8/site-packages/django_apscheduler/models.py:100: RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().
    help_text=_("Timestamp at which this job was finished."),

../../usr/lib/python3.8/site-packages/django_apscheduler/models.py:106
  /usr/lib/python3.8/site-packages/django_apscheduler/models.py:106: RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().
    help_text=_(

../../usr/lib/python3.8/site-packages/django_apscheduler/models.py:113
  /usr/lib/python3.8/site-packages/django_apscheduler/models.py:113: RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().
    help_text=_(

-- Docs: https://docs.pytest.org/en/stable/warnings.html
====================================================== short test summary info ======================================================
ERROR gsmap/tests.py::test_municipalities_exists - django.core.management.base.CommandError: No fixture named 'sites.site' found.
ERROR gsmap/tests.py::test_snapshots_exists - django.core.management.base.CommandError: No fixture named 'sites.site' found.
================================================= 324 warnings, 2 errors in 17.13s ==================================================
ERROR: 1
make[1]: *** [tests] Error 1
make: *** [tests] Error 2
</pre>
</details>

**Comment by glaand** [comment]
Fixed on https://github.com/cividi/spatial-data-package-platform/commit/a3d752986f799b6bfbdfdd398a00f9ccf172e495
